#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
# Jason Liu <r64343@freescale.com>
#
# SPDX-License-Identifier:      GPL-2.0+
#
# Adapted from freescale/mx53loco/Makefile by Andrej Rosano <andrej@inversepath.com>
# for USB armory (inversepath.com/usbarmory) hardware
#

obj-y			+= usbarmory.o
